---
title: "ECB Wander Study"
author: "James Brown"
date: "4/20/2018"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}

#knitr::opts_chunk$set(fig.path = "Images/")
```

##Call Data
````{r}
library(readxl)
library(ggplot2)
library(nlme)
library(lme4)
library(lmerTest)
library(ez)
library(lsr)
library(dplyr)
library(tidyr)
library(MASS)
library(doBy)
library(plyr)
library(ggplot2)
library(doBy)



##PC
data=read_excel("/Users/jbrown/Documents/GitHub/Lipid_Quantification/Data/Extraction Samples JLM.xlsx",sheet = "WANDER")


##MAC
## reading in the data and looking at its structure
#setwd("/Users/JamesB/Google Drive/Graduate School/Self_JamesTBrown/GitHub/Lipid_Quantification/Scripts_Analysis")
#data=read_excel("/Users/JamesB/Google Drive/Graduate School/Self_JamesTBrown/GitHub/Lipid_Quantification/Data/Extraction Samples JLM.xlsx", sheet = "WANDER")
data=subset(data,fifth_date!="NA")
#fifth_date= <- species[match(unique(species$Taxa), species$Taxa),]

#converting wide to long. This code puts all the observations into one column with the label of your choice (measurements used below)
all=gather(data,day,stage,"82wander_0616":"01wander_0327")
all$strain<-substr(all$tray_id,1,2)
all$strain<-as.factor(all$strain)
all$treat<-substr(all$tray_id,3,4)
all$treat<-as.factor(all$treat)
all$cohort<-substr(all$tray_id,6,9)
all$cohort<-as.factor(all$cohort)
#all$fiveday<-as.factor(all$fiveday)
#all$pday<-as.factor(all$pday)
#all$wday<-as.factor(all$wday)
all$day<-as.factor(all$day)
all$stage<-as.factor(all$stage)
all$tray_id<-as.factor(all$tray_id)
all$cell_id<-as.factor(all$cell_id)
all$fifth_date<-as.factor(all$fifth_date)

all=subset(all,stage!="NA")
```

##Distribution plots of larvae in the 5th instar by the amount of days it takes to reach the wandering stage with Linear Mixed Model analysis
```{r}
View(all)
ggplot(all, aes(x=wday,color=strain,group=strain))+
  geom_density(alpha=.2,adjust=2)+
  facet_wrap(~treat)+
  theme(axis.text.x  = element_text(vjust=0.5, size=16),axis.text.y  = element_text(vjust=0.5, size=16))+
  scale_x_continuous(breaks = seq(0, 17, by=5), limits=c(0,17))+
  scale_fill_manual(values=c("BE"="blue","UZ"="red"))+
  ggtitle("Days to Wandering Stage")
View(all)
summary(all)
modtreat=lmer(wday~treat*strain+(1|cohort),data=all,REML = TRUE)
summary(modtreat)
#step(modtreat)
plot(modtreat)
summary(modtreat)

all12=subset(all,treat==12)
summary(all12)
ggplot(all12, aes(x=wday,fill=strain))+
  geom_density(alpha=.3,adjust=2.5)+
  xlab("Days in 5th Instar")+
  theme_classic()+
  scale_x_continuous(breaks = seq(0, 20, by=1), limits=c(0,20))+
  geom_vline(xintercept = 10)+
  scale_fill_manual(values=c(UZ="purple",BE="orange"))+
  ggtitle("Diapause Conditions: Days to Wandering Stage")

mod12=lmer(wday~strain+(1|cohort),all12)
plot(mod12)
summary(mod12)
modaov12=aov(all12$wday~all12$strain)
summary(modaov12)


all16=subset(all,treat==16)
summary(all16)
  ggplot(all, aes(x=strain,y=wday))+
  stat_summary(aes(y = wday), fun.y=mean, geom="point", position="dodge",size=4)+
  stat_summary(fun.y=median, fun.ymin=function(x) median(x) - sd(x), 
               fun.ymax=function(x) median(x) + sd(x), geom="errorbar",position="dodge", width=0.1) +
  facet_wrap(~treat)+
  xlab("Days in 5th Instar")+
  theme_classic()+
  ggtitle("Non Diapause Conditions: Days to Wandering Stage")

mod16=lmer(wday~strain+(1|cohort),all16)
summary(all16)
summary(mod16)

mod12=lmer(wday~strain+(1|cohort),all12)
summary(all12)
summary(mod12)

unique(all$fifth_date)
```
##UZ 0302 Wandering and Pupation tracking by day
```{r}
##############################
##### Wandering Larvae? ######
##############################

######### "UZ16 0302" ################

data1=subset(all,tray_id=="UZ16 0302")
#data1=subset(data1,stage=="Y"| stage=="N")
#data1=subset(data1,day=="wander_0327"|day=="wander_0328"|day=="wander_0329"|day=="wander_0330"|day=="wander_0331"|day=="wander_0401"|day=="wander_0402"|day=="wander_0403"|day=="wander_0404")


ggplot(data=data1,aes(data1$wday))+
  geom_histogram(stat="count",binwidth=2, position="dodge")+
  xlab("Days in 5th Instar")+
  ggtitle("UZ16 0302 Wandering Day")

data1a=subset(all,tray_id=="UZ16 0302")
#data1a=subset(data1a,stage=="N"|stage=="P")
#data1a=subset(data1a,day=="wander_0327"|day=="wander_0328"|day=="wander_0329"|day=="wander_0330"|day=="wander_0331"|day=="wander_0401"|day=="wander_0402")

ggplot(data=data1a,aes(data1a$pday))+
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  xlab("Days in 5th Instar")+
  ggtitle("UZ16 0302 Pupation Day")

######### "UZ12 0302" ################

data2=subset(all,tray_id=="UZ12 0302")
#data2=subset(data2,stage=="N"|stage=="Y")

ggplot(data=data2,aes(data2$wday))+
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  xlab("Days in 5th Instar")+
  ggtitle("UZ12 0302 Wandering Day")



data2a=subset(all,tray_id=="UZ12 0302")
#data2a=subset(data2a,stage=="N"|stage=="P")
#data2a=subset(data2a,day=="wander_0327"|day=="wander_0328"|day=="wander_0329"|day=="wander_0330"|day=="wander_0331"|day=="wander_0401"|day=="wander_0402"|day=="wander_0402"|day=="wander_0403"|day=="wander_0404"|day=="wander_0405"|day=="wander_0406"|day=="wander_0407"|day=="wander_0408"|day=="wander_0409")

ggplot(data=data2a,aes(data2a$pday))+
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  xlab("Days in 5th Instar")+
  ggtitle("UZ12 0302 Rate of Wander No Pupation during the tracking period")
```
##BE 3014 Wandering and Pupation tracking by day
```{r}
######### "BE16 0314" ################

data3=subset(all,tray_id=="BE16 0314")
#data3=subset(data3,stage=="N"|stage=="Y")
#data3=subset(data3,day=="wander_0407"|day=="wander_0408"|day=="wander_0409"|day=="wander_0410"|day=="wander_0412"|day=="wander_0413"|day=="wander_0414"|day=="wander_0415"|day=="wander_0416"|day=="wander_0417"|day=="wander_0418"|day=="wander_0419")

ggplot(data=data3,aes(data3$wday))+
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  xlab("Days in 5th Instar")+
  ggtitle("BE16 0314 Wandering Day")


data3a=subset(all,tray_id=="BE16 0314")
#data3a=subset(data3a,stage=="N"|stage=="P")
#data3a=subset(data3a,day=="wander_0407"|day=="wander_0408"|day=="wander_0409"|day=="wander_0410"|day=="wander_0412"|day=="wander_0413"|day=="wander_0414"|day=="wander_0415"|day=="wander_0416"|day=="wander_0417"|day=="wander_0418"|day=="wander_0419")

ggplot(data=data3a,aes(data3a$pday))+
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  xlab("Days in 5th Instar")+
  ggtitle("BE16 0314 Pupation Day")


######### "BE12 0314" ################

data3b=subset(all,tray_id=="BE12 0314")
#data3b=subset(data3b,stage=="N"|stage=="Y")
#data3b=subset(data3b,day=="wander_0407"|day=="wander_0408"|day=="wander_0409"|day=="wander_0410"|day=="wander_0412"|day=="wander_0413"|day=="wander_0414"|day=="wander_0415"|day=="wander_0416"|day=="wander_0417"|day=="wander_0418"|day=="wander_0419"|day=="0420"|day=="0421")


ggplot(data=data3b,aes(data3b$wday))+
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  xlab("Days in 5th Instar")+
  ggtitle("BE12 0314 Wandering Day")

data3c=subset(all,tray_id=="BE12 0314")
#data3c=subset(data3c,stage=="N"|stage=="P")
#data3c=subset(data3c,day=="wander_0407"|day=="wander_0408"|day=="wander_0409"|day=="wander_0410"|day=="wander_0412"|day=="wander_0413"|day=="wander_0414"|day=="wander_0415"|day=="wander_0416"|day=="wander_0417"|day=="wander_0418"|day=="wander_0419"|day=="0420"|day=="0421")


ggplot(data=data3c,aes(data3c$pday))+
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  xlab("Days in 5th Instar")+
  ggtitle("BE12 0314 Pupation Day")
```
##BE 0320 Wandering and Pupation tracking by day
```{r}
######### "BE12 0320" ################

data4=subset(all,tray_id=="BE12 0320")
#data4=subset(data4,stage=="N"|stage=="Y")
#data4=subset(data4,day=="wander_0418"|day=="wander_0419"|day=="wander_0420"|day=="wander_0421"|day=="wander_0422"|day=="wander_0423"|day=="wander_0424"|day=="wander_0425")

ggplot(data=data4,aes(data4$wday))+
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  xlab("Days in 5th Instar")+
  ggtitle("BE12 0320 Wandering Day")


data4a=subset(all,tray_id=="BE12 0320")
#data4a=subset(data4a,stage=="N"|stage=="P")
#data4a=subset(data4a,day=="wander_0418"|day=="wander_0419"|day=="wander_0420"|day=="wander_0421"|day=="wander_0422"|day=="wander_0423"|day=="wander_0424"|day=="wander_0425")

ggplot(data=data4a,aes(data4a$pday))+
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  xlab("Days in 5th Instar")+
  ggtitle("BE12 0314 Pupation Day")

######### "BE16 0320" ################

data4b=subset(all,tray_id=="BE16 0320")
#data4b=subset(data4b,stage=="N"|stage=="P")
#data4b=subset(data4b,day=="wander_0418"|day=="wander_0419"|day=="wander_0420"|day=="wander_0421"|day=="wander_0422"|day=="wander_0423"|day=="wander_0424"|day=="wander_0425")

#summ=ddply(data4b, c("stage"), summarise,
 #          N    = sum(!is.na(stage)),
  #         mean = mean(stage, na.rm=TRUE),
   #        sd   = sd(stage, na.rm=TRUE),
    #       se   = sd / sqrt(N))

ggplot(data=data4b,aes(data4b$wday))+
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  xlab("Days in 5th Instar")+
  ggtitle("BE16 0320 Wandering Day")

data4c=subset(all,tray_id=="BE16 0320")
#data4c=subset(data4c,stage=="N"|stage=="Y")
#data4c=subset(data4c,day=="wander_0418"|day=="wander_0419"|day=="wander_0420"|day=="wander_0421"|day=="wander_0422"|day=="wander_0423"|day=="wander_0424"|day=="wander_0425")

#summ=ddply(data4c, c("stage"), summarise,
 #          N    = sum(!is.na(stage)),
  #         mean = mean(stage, na.rm=TRUE),
   #        sd   = sd(stage, na.rm=TRUE),
    #       se   = sd / sqrt(N))

ggplot(data=data4c,aes(data4c$pday))+
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  xlab("Days in 5th Instar")+
  ggtitle("BE16 0320 Pupation Day")

```
##Stages of Life History across time
`````{r}
#############
ggplot(all, aes(x=fiveday,fill=treat))+
  geom_density(alpha=.3)+
  xlab("Days to 5th Instar")+
  ggtitle("Timing of 5th Instar")

ggplot(all, aes(x=fiveday,fill=strain))+
  geom_density(alpha=.3)+
  facet_grid(strain~treat)+
  xlab("Days to 5th Instar")+
  ggtitle("Timing of 5th Instar")
```

## Other Plots
```{r}
ggplot(all, aes(x=pday, fill=treat))+
  geom_density(alpha=.3)+
  xlab("Days in 5th Instar")+
  ggtitle("Days to Pupation")

ggplot(all, aes(x=pday, fill=strain))+
  geom_density(alpha=.3)+
  facet_grid(strain~treat)+
  xlab("Days in 5th Instar")+
  ggtitle("Days to Pupation")
##RAW GRAPHS


##############################
######### WANDERS ############
##############################
allw=subset(all,stage=="Y")
ggplot(data=allw, aes(allw$wday,fill=tray_id,group=tray_id)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge") +
  scale_x_discrete(breaks=c("wander_0327","wander_0328","wander_0329","wander_0330","wander_0331","wander_0401","wander_0402","wander_0403","wander_0404", "wander_0405", "wander_0406","wander_0407","wander_0408","wander_0409","wander_0410","wander_0411","wander_0412","wander_0413", "wander_0414","wander_0415","wander_0416","wander_0417","wander_0418","wander_0419","wander_0420","wander_0421","wander_0422","wander_0423","wander_0424","wander_0425","wander_0426","wander_0427","wander_0428","wander_0429","wander_0430","wander_0501","wander_0502","wander_0503","wander_0504","wander_0505","wander_0506","wander_0507","wander_0526","wander_0527","wander_0528","wander_0529","wander_0530","wander_0531","wander_0601","wander_0602","wander_0603","wander_0604","wander_0605","wander_0604","wander_0603","wander_0604","wander_0605","wander_0606","wander_0607","wander_0608","wander_0609","wander_0610","wander_0611","wander_0612"),
                      labels=c("1":"64"))
```

```{r}
#uz12 Includes all the 5th dates for this cohort
uz0302a=subset(all,stage=="Y")
uz0302a=subset(uz0302a,tray_id=="UZ12 0302")
#uz0302a=subset(uz0302a,day=="wander0327"|day=="wander_0328"|day=="wander_0329"|day=="wander_0330"|day=="wander_0331"|day=="wander_0401"|day=="wander_0402"|day=="wander_0403"|day=="wander_0404"|day=="wander_0405"|day=="wander_0406")
unique(uz0302a$fifth_date)
ggplot(data=uz0302a, aes(fifth_date, fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("UZ12 0302")
  

#uz12 Removes 5th dates with relatively low larvae numbers
uz0302b=subset(all,stage=="Y")
uz0302b=subset(uz0302b,fifth_date=="20180323"|fifth_date=="20180324"|fifth_date=="20180325")
uz0302b=subset(uz0302b,tray_id=="UZ12 0302")
#uz0302b=subset(uz0302b,day=="wander_0327"|day=="wander_0328"|day=="wander_0329"|day=="wander_0330"|day=="wander_0331"|day=="wander_0401"|day=="wander_0402"|day=="wander_0403"|day=="wander_0404"|day=="wander_0405"|day=="wander_0406")
unique(uz0302b$fifth_date)
ggplot(data=uz0302b, aes(fifth_date, fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("UZ12 0302: Removed 03/26 03/27 03/28")
```

```{r}
#uz16 Includes all the 5th dates for this cohort
uz0302c=subset(all,stage=="Y")
uz0302c=subset(uz0302c,tray_id=="UZ16 0302")
#uz0302c=subset(uz0302c,day=="wander_0327"|day=="wander_0328"|day=="wander_0329"|day=="wander_0330"|day=="wander_0331")
ggplot(data=uz0302c, aes(fifth_date, fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("UZ16 0302")

#uz16 Removes 5th date with relatively low larvae numbers
uz0302d=subset(all,stage=="Y")
uz0302d=subset(uz0302d,fifth_date=="20180323"|fifth_date=="20180324")
uz0302d=subset(uz0302d,tray_id=="UZ16 0302")
#uz0302d=subset(uz0302d,day=="wander_0327"|day=="wander_0328"|day=="wander_0329"|day=="wander_0330"|day=="wander_0331")
ggplot(data=uz0302d, aes(fifth_date, fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("UZ16 0302: Removed 03/25")
```

```{r}
#be12 will all 5th dates
be0314a=subset(all,stage=="Y")
unique(be0314a$fifth_date)
be0314a=subset(be0314a,tray_id=="BE12 0314")
#be0314a=subset(be0314a,day=="wander_0410"|day=="wander_0411"|day=="wander_0412"|day=="wander_0413"|day=="wander_0414"|day=="wander_0415"|day=="wander_0416"|day=="wander_0417")
ggplot(data=be0314a, aes(be0314a$fifth_date,fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("BE12 0314")

#be12 Removes 5th dates with relatively low larvae numbers
be0314b=subset(all,stage=="Y")
be0314b=subset(be0314b,fifth_date=="20180406"|fifth_date=="20180407")
be0314b=subset(be0314b,tray_id=="BE12 0314")
#be0314b=subset(be0314b,day=="wander_0410"|day=="wander_0411"|day=="wander_0412"|day=="wander_0413"|day=="wander_0414"|day=="wander_0415"|day=="wander_0416"|day=="wander_0417")
ggplot(data=be0314b, aes(be0314b$fifth_date,fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("BE12 0314: Removed 04/05 04/10")

#be16 will all 5th dates
be0314c=subset(all,stage=="Y")
be0314c=subset(be0314c,tray_id=="BE16 0314")
#be0314c=subset(be0314c,day=="wander_0410"|day=="wander_0411"|day=="wander_0412"|day=="wander_0413"|day=="wander_0414"|day=="wander_0415"|day=="wander_0416"|day=="wander_0417")
ggplot(data=be0314c, aes(be0314c$fifth_date,fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("BE16 0314")

#be16 Removes 5th dates with relatively low larvae numbers
be0314d=subset(all,stage=="Y")
be0314d=subset(be0314d,fifth_date=="20180406"|fifth_date=="20180407"|fifth_date=="20180408"|fifth_date=="20180409")
be0314d=subset(be0314d,tray_id=="BE16 0314")
#be0314d=subset(be0314d,day=="wander_0410"|day=="wander_0411"|day=="wander_0412"|day=="wander_0413"|day=="wander_0414"|day=="wander_0415"|day=="wander_0416"|day=="wander_0417")
ggplot(data=be0314d, aes(be0314d$fifth_date,fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("BE16 0314: Removed 04/05 04/10")

#be12 will all 5th dates
be0320a=subset(all,stage=="Y")
be0320a=subset(be0320a,tray_id=="BE12 0320")
unique(be0320a$fifth_date)
be0320a=subset(be0320a,fifth_date=="20180412"|fifth_date=="20180413"|fifth_date=="20180414"|fifth_date=="20180415"|fifth_date=="20180416")
#be0320a=subset(be0320a,day=="wander_0418"|day=="wander_0419"|day=="wander_0420"|day=="wander_0421"|day=="wander_0422")
ggplot(data=be0320a, aes(be0320a$fifth_date,fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("BE12 0320")

#be16 will all 5th dates
be0320c=subset(all,stage=="Y")
be0320c=subset(be0320c,tray_id=="BE16 0320")
unique(be0320c$fifth_date)
be0320c=subset(be0320c,fifth_date=="20180412"|fifth_date=="20180413"|fifth_date=="20180414"|fifth_date=="20180415")
#be0320c=subset(be0320c,day=="wander_0416"|day=="wander_0417"|day=="wander_0418"|day=="wander_0419"|day=="wander_0420"|day=="wander_0421"|day=="wander_0422"|day=="wander_0423"|day=="wander_0424")
ggplot(data=be0320c, aes(be0320c$fifth_date,fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("BE16 0320")

#be16 Removes 5th dates with relatively low larvae numbers
be0320c=subset(all,stage=="Y")
be0320c=subset(be0320c,tray_id=="BE16 0320")
unique(be0320c$fifth_date)
be0320c=subset(be0320c,fifth_date=="20180413"|fifth_date=="20180414"|fifth_date=="20180415")
#be0320c=subset(be0320c,day=="wander_0416"|day=="wander_0417"|day=="wander_0418"|day=="wander_0419"|day=="wander_0420"|day=="wander_0421"|day=="wander_0422"|day=="wander_0423"|day=="wander_0424")
ggplot(data=be0320c, aes(be0320c$fifth_date,fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("BE16 0320: Removed 04/12")

#be12 will all 5th dates
be0429a=subset(all,stage=="Y")
be0429a=subset(be0429a,tray_id=="BE12 0429")
be0429a=subset(be0429a,fifth_date=="20180520"|fifth_date=="20180521"|fifth_date=="20180522"|fifth_date=="20180523")
#be0429a=subset(be0429a,day=="wander_0605" |day=="wander_0604" |day=="wander_0603" |day=="wander_0602" |day=="wander_0601"|day=="wander_0531"|day=="wander_0530" |day=="wander_0529" |day=="wander_0528")
ggplot(data=be0429a, aes(be0429a$fifth_date,fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("BE12 0429")
unique(be0429a$day)

#be12 Removes 5th dates with relatively low larvae numbers
be0429b=subset(all,stage=="Y")
be0429b=subset(be0429b,tray_id=="BE12 0429")
be0429b=subset(be0429b,fifth_date=="20180521"|fifth_date=="20180522"|fifth_date=="20180523")
#be0429b=subset(be0429b,day=="wander_0605"|day=="wander_0604"|day=="wander_0603"|day=="wander_0602"|day=="wander_0601"|day=="wander_0531"|day=="wander_0530" |day=="wander_0529" |day=="wander_0528")
ggplot(data=be0429b, aes(be0429b$fifth_date,fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("BE12 0429: Removed 05/20")

#be16 will all 5th dates
be0429c=subset(all,stage=="Y")
be0429c=subset(be0429c,tray_id=="BE16 0429")
be0429c=subset(be0429c,fifth_date=="20180520"|fifth_date=="20180521"|fifth_date=="20180522")
#be0429c=subset(be0429c,day=="wander_0601"|day=="wander_0531"|day=="wander_0530"|day=="wander_0529"|day=="wander_0528"|day=="wander_0527")
ggplot(data=be0429c, aes(be0429c$fifth_date,fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("BE16 0429")

#be16 Removes 5th dates with relatively low larvae numbers
be0429d=subset(all,stage=="Y")
be0429d=subset(be0429d,tray_id=="BE16 0429")
be0429d=subset(be0429d,fifth_date=="20180521"|fifth_date=="20180522")
#be0429d=subset(be0429d,day=="wander_0601"|day=="wander_0531"|day=="wander_0530"|day=="wander_0529"|day=="wander_0528"|day=="wander_0527")
ggplot(data=be0429d, aes(be0429d$fifth_date,fill=day)) + 
  geom_histogram(stat="count",binwidth=1, position="dodge")+
  ggtitle("BE16 0429: Removed 05/20")
```

```{r}
##Animated Plots

#theme_set(theme_bw())  # pre-set the bw theme.

#g <- ggplot(data, aes(gdpPercap, lifeExp, size = pop, frame = diapause))+
#geom_point() +
 # geom_smooth(aes(group = cohort), 
  #            method = "lm", 
 #             show.legend = FALSE) +
#  facet_wrap(~continent, scales = "free") 
#gganimate(g, interval=0.2)

```